findLineCoords
getTargets
starRoutine
%Use visualExam to generate plots to pick out bad lines by eye. 
%Use second column as 1/0 filter for good/bad lines
%visualExam will raise an error after making graphs.
visualExam; 
T = csvread('Sun/goodLines.csv'); %generated by visualExam, modified by user
lineFilter = logical(T(:, 2));
save Sun/lineFilter.mat lineFilter
buildModel
testModelAllStars